### ISSUE TITLE
Installed but "git: 'hours' is not a git command" 

### ISSUE THREAD

**Issue by kontur** [kimmobrunfeldt/git-hours#33]
I tried installing this helper. From what I can tell both git-hours:

```
$ npm list -g | grep git-hours
├─┬ git-hours@1.3.0
```
and nodegit:

```
$ npm list -g | grep nodegit
│ └─┬ nodegit@0.13.2
│     └─┬ nodegit-promise@4.0.0
└─┬ nodegit@0.20.3
    └─┬ nodegit-promise@4.0.0
```

seem installed. However, when I run `$ git hours` in a git repository root I get this message:

> 
> $ git hours
> git: 'hours' is not a git command. See 'git --help'.

My npm version is 5.6.0, my node is 9.5.0.

**Comment by KernelDeimos** [comment]
One time somebody I know began a Facebook post with "We only have koi eating otters in Canada . . ."

I was astonished by the idea that koi could eat otters. That seemed absolutely crazy to me and I thought there was no way that could be true. I was right - he just forgot the hyphen in "koi-eating otters"

Anyway, I think you meant `git-hours`

**Comment by kontur** [comment]
Hm. All of the documentation reads `$ git hours` - which is probably where my wrong assumption came from?

**Comment by KernelDeimos** [comment]
Oh, I didn't even realize that. I bet @kimmobrunfeldt has it set like that in his git config or something

**Comment by kontur** [comment]
Nah, I've since seen other modules for git defined as `git-something` and they are then available as `$ git something` — it just was not obvious to me when I tried to establish if the module was installed. I can't say which now `$ git hours` works for me — could this be to do with the git version?

**Comment by mhashim6** [comment]
same for me.

**Comment by tobius** [comment]
You can turn `git hours` into a real command by configuring it as a git alias. My guess is that's why it's being recommended to install `git-hours` globally. For example this would work:

```shell
[~] npm i -g git-hours
[~] git config --global alias.hours 'npx git-hours'
```

However, I never recommend using global installs because it interferes with version switching activities (e.g. via `nvm`). I would recommend doing something like this instead:

**Install git-hours inside your project (as a devDependency)**

```shell
[~] cd project
[~/project] nvm use 12
[~/project] npm i -D git-hours
```

_Note: This project works for me in Node 12, compiles in 14 but is ridiculously slow, and fails in 16._

**Add `hours` script command to your project**

`package.json`
```json
{
  "scripts": {
    "hours": "npx git-hours"
  }
}
```

Now you can include `npm run hours` as part of your project.

---

_Tip: If you're not already adding `.nvmrc`, `.npmrc`, and `package.json:engines` declarations in your projects to let other Developers know which version of Node.js your project should be built and executed with I highly recommend adding this as a new best practice._

**Comment by kimmobrunfeldt** [comment]
After new release 1.5.0, `npx git-hours` works again! Tested with node 14, macOS. The node version is probably quite specific.

**Comment by kimmobrunfeldt** [comment]
It used to work by default with a space separation, not sure about today. Updated guides to still use the dash version.
